config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # resources :articles

  root 'articles#index'
  get '/articles' => 'articles#index'
  get '/articles/new' => 'articles#new', as: 'new_article'
  post '/articles' => 'articles#create', as: 'create_article'
  get '/articles/edit' => 'articles#edit', as: 'edit_article'
  post '/articles/delete' => 'articles#delete', as: 'delete_article'
  post '/articles/update' => 'articles#update', as: 'update_article'
  get '/articles/show' => 'articles#show', as: 'show_article'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    skip_before_action :verify_authenticity_token

    def index
        @articles = Article.all
    end

    def show
        @article = Article.find(params[:id])
    end

    def new
        @article = Article.new
    end

    def create
        @article = Article.new(article_params)
        @article.name = params[:article][:name]
        
        if @article.save
            redirect_to articles_path
        else
            render :new
        end
    end

    def edit
        @article = Article.find(params[:id])
    end

    def update
        @article = Article.find(params[:id])

        if @article.update(article_params)
            redirect_to articles_path
        else
            render :edit
        end
    end

    def delete
        @article = Article.find(params[:id])

        if @article.destroy
            redirect_to articles_path
        else
            render :edit
        end
    end

    private
    def article_params
        params.require(:article).permit(:name, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<%= stylesheet_link_tag 'style.css' %>
<%= form_for(:article) do |f| %>

<div>
<h1>Edit Article: <%=@article.name%></h1>
    <% if @article.errors.any? %>
        <ul>
            <% @article.errors.full_messages.each do |message| %>
                <li>
                    <%= message%>
                </li>
            <% end %>
        </ul>
    <% end %>
</div>

<div>
    <%= f.label :name %>
    <%= f.text_field :name , value: @article.name %>
</div>

<div>
    <%= f.label :body %>
    <%= f.text_area :body , value: @article.body %>
</div>

<div class="form-submit">
    <%= hidden_field_tag(:id, @article.id) %>
    <%= f.submit 'Update', formaction: update_article_path%>
    <%= f.submit 'Delete', formaction: delete_article_path, data: { confirm: 'Are you sure you want to delete this article?' }%>
</div>

<% end %>

<%= link_to 'Back to Articles', articles_path, class: "btn-link-to"%>

app/views/articles/index.html.erb
<%= stylesheet_link_tag 'style.css' %>
<h1> Charles' Articles </h1>
<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Title</th>
            <th>Body</th>
            <th class="table-btns">Show</th>
            <th class="table-btns">Edit</th>
        </tr>
    </thead>

    <tbody>
        <% @articles.each do |article|%>
            <tr>
                <td><%= article.id%></td>
                <td><%= article.name%></td>
                <td><%= article.body%></td>
                <td><%= link_to 'Show', show_article_path(:id => article.id)%></td>
                <td><%= link_to 'Edit', edit_article_path(:id => article.id)%></td>
            </tr>
        <% end %>
    </tbody>
</table>

<%= link_to 'New Article', new_article_path, class: "btn-link-to"%>

app/views/articles/new.html.erb
<%= stylesheet_link_tag 'style.css' %>

<%= form_with scope: :article, url: create_article_path, local: true do |f| %>

<h1>New Article</h1>

<div>
    <% if @article.errors.any? %>
        <ul>
            <% @article.errors.full_messages.each do |message| %>
                <li>
                    <%= message%>
                </li>
            <% end %>
        </ul>
    <% end %>
</div>

<div>
    <%= f.label :name, "Name:" %>
    <%= f.text_field :name %>
</div>

<div>
    <%= f.label :body, "Body:" %>
    <%= f.text_area :body %>
</div>

<div class="form-submit">
    <%= f.submit %>
</div>

<% end %>

<%= link_to 'Back to Articles', articles_path, class: "btn-link-to" %>

app/views/articles/show.html.erb
<%= stylesheet_link_tag 'style.css' %>

<div class="show-div">
    <h1><%= @article.name%></h1>
    <p><%= @article.body%></p>
</div>

<%= link_to 'Back to Articles', articles_path, class: "btn-link-to"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>